# Generated by Django 6.0.3 on 2026-04-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcore', '0004_supplier_stockentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescriber',
            field=models.CharField(blank=True, help_text='Doctor who issued the prescription', max_length=150),
        ),
    ]
