# Generated by Django 6.0.3 on 2026-04-20 14:23

from django.db import migrations


def migrate_prescription_data(apps, schema_editor):
    Prescription = apps.get_model('pharmcore', 'Prescription')
    PrescriptionItem = apps.get_model('pharmcore', 'PrescriptionItem')
    for p in Prescription.objects.all():
        if p.medicine_id and not p.items.exists():
            PrescriptionItem.objects.create(
                prescription=p,
                medicine_id=p.medicine_id,
                quantity=p.quantity,
                dosage=p.dosage
            )

class Migration(migrations.Migration):

    dependencies = [
        ('pharmcore', '0006_alter_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_prescription_data),
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity',
        ),
    ]
