# Generated by Django 6.0.3 on 2026-04-20 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmcore', '0007_remove_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescriber',
            field=models.ForeignKey(blank=True, help_text='Staff member who recorded/issued the prescription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
